version: 2.0
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: 
          name: Install project dependencies
          command: npm install
      - run:
          name: Run consumer contract tests
          command: npm run test:consumer
      - run:
          name: Publish contract to Pactflow
          command: npm run publish:pact
      - run:
          name: Run provider contract tests
          command: npm run test:provider

workflows:
    build-and-test:
      jobs:
        - build:
            context: org-global
